### ISSUE TITLE
How to select context storage?

### ISSUE THREAD

**Issue by Swiftnesses** [cflurin/node-red-contrib-dsm#12]
By default by NR instance is set to use memory as the default context, with a disk store which is used when required... how can I ensure this node uses the disk context?

**Comment by Swiftnesses** [comment]
I guess this is no longer being developed :-(

**Comment by cflurin** [comment]
Please, ask in the node-red forum. This is not a dsm issue!  You should take the time to read the doc 😉

**Comment by Swiftnesses** [comment]
Thanks for the response :)

I have disk set as my secondary contextStorage in NR, I cannot work out how to make sure DSM uses this contextStorage and not the default (in my case memory).

**Comment by cflurin** [comment]
Please got to the node-red forum:

https://discourse.nodered.org/

**Comment by Swiftnesses** [comment]
This is a DSM issue, not a NR issue.

Thanks for the help 👎

**Comment by cflurin** [comment]
Open source doesn't mean that you can always get free help from the developer. I have spent a lot of time developing this node.
As I said you can get help in the node-red-forum.
