### ISSUE TITLE
Operating time dsm giving two consecutives "off" msg.topic 

### ISSUE THREAD

**Issue by peppe-terra** [cflurin/node-red-contrib-dsm#13]
I'm using your dsm operating time (exactly the code in the wiki) to calculate the time when my device is on. If I send consecutively two msg.topic setted to "off", the first stop the counter (right) but the second increases the counter of the time between the first and the second "off".
According to the defined states I expected that a "off" sent when the dsm is stopped would not causes anything to the counter.

**Comment by cflurin** [comment]
Strange, it works for me.
Can you upload your flow here.

Note: Please download your uploaded flow again and import it in node-red to be sure that I can import your flow.

**Comment by peppe-terra** [comment]
Here you are. Very simple.

`[{"id":"a42e1b17.a22748","type":"tab","label":"DSM","disabled":false,"info":""},{"id":"80f4533a.d432","type":"dsm","z":"a42e1b17.a22748","name":"","sm_config":"{\n    \"currentState\": \"stopped\",\n    \"states\": {\n        \"stopped\": {\n            \"on\": \"started\"\n        },\n        \"started\": {\n            \"inc\": \"counting\",\n            \"off\": \"stopped\"\n        },\n        \"counting\": {\n            \"inc\": \"counting\",\n            \"off\": \"stopped\"\n        }\n    },\n    \"data\": {\n        \"prev_time\": null,\n        \"time\": 0,\n        \"seconds\": 0,\n        \"interval\": 1,\n        \"interval_output\": true,\n        \"hms_format\": true\n    },\n    \"methods\": {\n        \"init\": [\n            \"sm.calc_time = function() {\",\n            \"   var now = Date.now();\",\n            \"   sm.data.time += now - sm.data.prev_time;\",\n            \"   sm.data.prev_time = now;\",\n            \"   sm.data.seconds = Math.round(sm.data.time / 1000);\",\n            \"};\",\n            \"sm.sec2hhmmss = function(sec) {\",\n                \"var t = {};\",\n                \"t.h = pad(Math.floor(sec / 3600));\",\n                \"sec %= 3600;\",\n                \"t.m = pad(Math.floor(sec / 60));\",\n                \"t.s = pad(sec % 60);\",\n                \"return t.h+':'+t.m+':'+t.s;\",\n            \"};\"\n        ],\n        \"on\": [\n            \"if (sm.currentState === 'started') {\",\n            \"   sm.data.prev_time = Date.now();\",\n            \"   resume('inc', msg);\",\n            \"}\",\n            \"output = false;\"\n        ],\n        \"inc\": [\n            \"timeout.interval = setTimeout(function() {\",\n            \"   sm.calc_time();\",\n            \"   msg.data = sm.data;\",\n            \"   if (sm.data.interval_output) {\",\n            \"       msg.payload = sm.data.hms_format ? sm.sec2hhmmss(sm.data.seconds): sm.data.seconds;\",\n            \"       node.send(msg);\",\n            \"   }\",\n            \"   resume('inc', msg);\",\n            \"}, sm.data.interval*1000);\",\n            \"output = false;\"\n        ],\n        \"off\": [\n            \"clearTimeout(timeout.interval);\",\n            \"sm.calc_time();\",\n            \"msg.payload = sm.data.hms_format ? sm.sec2hhmmss(sm.data.seconds): sm.data.seconds;\"\n        ],\n        \"reset\": [\n            \"sm.data.time = 0;\",\n            \"sm.data.seconds = 0;\"\n        ],\n        \"status\": {\n            \"fill\": {\n                \"get\": \"sm.currentState === 'counting' ? 'green' : 'grey';\"\n            },\n            \"shape\": \"dot\",\n            \"text\": {\n                \"get\": \"'time ' + (sm.data.hms_format ? sm.sec2hhmmss(sm.data.seconds): sm.data.seconds);\"\n            }\n        }\n    }\n}","x":430,"y":240,"wires":[[]]},{"id":"ca70ee6f.015ff","type":"inject","z":"a42e1b17.a22748","name":"","topic":"reset","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":140,"wires":[["80f4533a.d432"]]},{"id":"99a0b7a6.aebe48","type":"inject","z":"a42e1b17.a22748","name":"","topic":"on","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":220,"y":200,"wires":[["80f4533a.d432"]]},{"id":"a4a20b4.2a573f8","type":"inject","z":"a42e1b17.a22748","name":"","topic":"off","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":280,"wires":[["80f4533a.d432"]]}]`

**Comment by cflurin** [comment]
Okey, I see the status isn't correct but add a debug node and you'll see the output works correctly.

I'll have a look at the status later

**Comment by peppe-terra** [comment]
The output is not given with the second off, but if you restart the counter it continues to count from the time shown in the status...

**Comment by cflurin** [comment]
Well, this use case of the dsm is just an implementation showing the power of this node. Feel free to modify it for your requirements.

**Comment by peppe-terra** [comment]
Ok, thank you.
