### ISSUE TITLE
dsm undefined error

### ISSUE THREAD

**Issue by 6wheels** [cflurin/node-red-contrib-dsm#2]
Hi,

Thanks for this great Node-RED node!
I used your home security example as a base for my home security system.

However, I have an issue since the update to 0.10.2. When starting Node-RED, I get the error: `3 Sep 14:53:15 - [error] [dsm:security_system] TypeError: Cannot read property 'req' of undefined`.
I cannot inject or use any of the dsm nodes anymore.
I have to downgrade to 0.10.0.
Please tell me if you need more information.

**Comment by cflurin** [comment]
Hi,
Thanks for your feedback.

Actually I've fixed this issue yesterday but didn't publish a new version.

Please install v0.10.3, it should be available in the next few minutes.
Or install from GibHub.

**Comment by 6wheels** [comment]
Fixed in 0.10.3.
Thanks @cflurin
