### ISSUE TITLE
Question: restore state from context storage

### ISSUE THREAD

**Issue by 6wheels** [cflurin/node-red-contrib-dsm#3]
Hello,

I would like to restore some of my DSM node statuses when Node-RED starts.

Currently, as mentioned in the documentation, I set up a simple inject node to inject the right status according to the stored values. But with the other "set" nodes which inject the configuration in each DSM node, the statuses seem to be overwritten.

Should I avoid using the "set" nodes? Or is there another smarter way to achieve this?

Thanks again for your time.

EDIT: I forgot to say that I used the `globalOutput` setting to store the value in the global storage.

**Comment by cflurin** [comment]
Have a look at the Wiki:
https://github.com/cflurin/node-red-contrib-dsm/wiki/contextStorage

**Comment by 6wheels** [comment]
@cflurin I tried the given example, but it does not seem to work with my flow. Actually my flow is nearly the same as your Security system example.
At first, I thought that the first inject node for arming, in JSON was causing a problem so I changed its payload to a simple string, but it still does not work.
Secondly, I thought that maybe the link nodes where causing a problem, but without them, it does not work either. 
Finally, I deleted the `globalOutput` setting, but still bot working.

I'm sorry, I'm a bit lost...
What should restore the state? The topic set in the inject node? Should it be set to a transition name?

Tell me if you need my flow to be able debug.
Thanks

**Comment by 6wheels** [comment]
Ok, I've just figured it out!

The inject nodes responsible for setting up the DSM nodes were configured to inject the message once after 0,1 seconds. This is what resets the state in my DSM nodes.

So, currently your security system example cannot work with contextStorage.

Closing, thanks again for your time.

**Comment by cflurin** [comment]
Hi,
Ok, feel free to update your flow if you need further help.
