### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by drmibell** [cflurin/node-red-contrib-dsm#5]
Recent discussion [https://discourse.nodered.org/t/another-dsm-question-same-trigger-different-transitions/4768](url) suggests that a couple of simple modifications of the `dsm` node would let the user employ downstream nodes to implement actions (methods) based on the machine state or on specific transitions. By default, the node sends a message each time it changes state. Two changes to this message would make it possible to determine the current and previous states of the machine and to identify the specific transition that occurred. 

First, the default `stateOutput` is `topic`, but this over-writes the incoming `triggerInput`. If `stateOutput` defaults instead to (for example) `current`, then the information about which transition was triggered would be preserved.

Second, it would be simple to identify the state of the machine before the transition by adding it to the message as `msg.previous`. I have implemented this by adding just one line of code, and it seems to work.

The result is a message like {"_msgid":"96f3c7c9.fb5e68","topic":"trigger","payload":1542305299262,"previous":"state1","current":"state2"}.

This would allow the user to create entry, exit, state, or transition actions until such time as they are implemented within the `dsm` node itself. There may also be actions that would be difficult to create within the node, such as managing communication channels or controlling other state machines, so these modifications could continue to be valuable.

**Comment by cflurin** [comment]
Hi @drmibell,

Thanks for your feedback. 

> First, the default `stateOutput` is `topic`, but this over-writes the incoming `triggerInput`. If `stateOutput` defaults instead to (for example) `current`, then the information about which transition was triggered would be preserved.
> 
You can overwrite the default and set `stateOutput` to `current` (= msg.current)

> Second, it would be simple to identify the state of the machine before the transition by adding it to the message as `msg.previous`. I have implemented this by adding just one line of code, and it seems to work.
> 

I'll have look tomorrow, I think I will add some more parameters like `previousState` to use in the dsm methods as well as  `previousStateOutput` so you can set the msg properties you need.

```
    "stateOutput": "current",
    "previousStateOutput": "previous",
```

**Comment by drmibell** [comment]
That sounds good. I only suggested changing the defaults so that it would work "out of the box." Changing the default for `stateOutput` might actually break some existing flows, so your idea is probably better.

**Comment by cflurin** [comment]
@drmibell 

I've uploaded a new version to github:
new `preState` and `preStateOutput`, have a look at README

Please, install from github if you'd like to test it.

**Comment by drmibell** [comment]
It seems to work nicely. Thanks.
