### ISSUE TITLE
Initial state definition

### ISSUE THREAD

**Issue by drmibell** [cflurin/node-red-contrib-dsm#6]
Two issues related to the initial state:
1. If the node is deployed with no configuration and one is injected with `msg.topic` = "set", the node status is "dsm ready", but the initial state is not shown as it would be if the configuration JSON were entered in the node edit window. It would be helpful to display this information in this case also.
2. It seems that the `currentState` definition is required in the configuration. It might work to enter the first state in the `states` list by default, or to display an error message that identifies the problem.

**Comment by cflurin** [comment]
Hi @drmibell,

1. As soon as a transition is executed the status is updated, I should be the same as with configuration.

2. Right, the `currrentState` is required. I'll have a look and add an error-handling for this case.

**Comment by drmibell** [comment]
Sorry! 

I was sure that I had seen the second (right) node in this flow display its status as "state1" when first deployed. I must have been mistaken. However, it has a check mark, which the one on the left does not, even thought they are both in the same state. I assume this means that the configuration JSON 
has been validated. This might be useful for an injected configuration also. Finally, I still think it would be good for the node to show its state when first deployed so that the user doesn't have to force a transition in order to see what state the node is in.
```
[{"id":"96c4f905.78da","type":"dsm","z":"19ee1d53.46284b","name":"","sm_config":"","x":370,"y":460,"wires":[[]]},{"id":"2b66e761.2b97a8","type":"inject","z":"19ee1d53.46284b","name":"set","topic":"set","payload":"{\"currentState\":\"state1\",\"states\":{\"state1\":{\"trigger\":\"state2\"},\"state2\":{\"trigger\":\"state3\"},\"state3\":{\"trigger\":\"state1\"}}}","payloadType":"json","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":230,"y":460,"wires":[["96c4f905.78da"]]},{"id":"a74b8b00.3470f8","type":"dsm","z":"19ee1d53.46284b","name":"","sm_config":"{\n    \"currentState\": \"state1\",\n    \"states\": {\n        \"state1\": {\n            \"trigger\": \"state2\"\n        },\n        \"state2\": {\n            \"trigger\": \"state3\"\n        },\n        \"state3\": {\n            \"trigger\": \"state1\"\n        }\n    }\n}","x":510,"y":460,"wires":[[]]}]
```

**Comment by cflurin** [comment]
I see, this `check mark` is confusing, it is actually set in the html file by a node with an configuration, no check mark if the configuration is empty. I'll see if I can find another symbol or character.

Indeed, the state should be shown in the status. I don't remember the reason, probably because you can run a dsm node without any states also only with methods. I'll have a look and see what I can do. Actually it will be useful to display the current state.

I have added several features during the development and had to change and test the functionality several times.

So your feedback is really useful, thank you.

**Comment by cflurin** [comment]
@drmibell 
Ok I've uploaded a new version with some improvement to GitHub.

**Comment by drmibell** [comment]
Nice. You have really made clear what is happening. 

I'm glad you found the comments helpful. I try not to sound too critical, but I'm not always sure how it comes across.
